apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::473474156106:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1NB3ECKQ211HP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::473474156106:role/UdacityFlaskDeployCBKubectlRole
      username: admin
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-17T23:54:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1352"
  uid: 17196d34-c706-4154-997f-6da553054122
